### ISSUE TITLE
Does it still depend on gtk3?

### ISSUE THREAD

**Issue by archisman-panigrahi** [phase1geo/Annotator#111]
This line in meson.build seems to have something to do with gtk3. Does annotator still depend on gtk3?

https://github.com/phase1geo/Annotator/blob/edcb5146b4ffc43f171c9fb6c309267643f9f133/meson.build#L41

**Comment by phase1geo** [comment]
It does not have a Gtk3 dependency.  That is old, unused code that I'll remove.

**Comment by phase1geo** [comment]
The meson.build file no longer contains references to Gtk-3.  The master branch has been updated accordingly.

**Comment by archisman-panigrahi** [comment]
Thank you
