### ISSUE TITLE
Missing keybindings

### ISSUE THREAD

**Issue by QWxleA** [phase1geo/Annotator#15]
Can anything be done with keybindings? It would be more convenient. Great app, btw

**Comment by phase1geo** [comment]
To some degree there are keybindings. I will need to create a cheat sheet for those in the app.

**Comment by phase1geo** [comment]
The master branch has been updated to include a keyboard shortcut cheatsheet.  I have also added a number of keyboard shortcuts for creating annotation items.  The cheatsheet contains these new shortcuts.

**Comment by QWxleA** [comment]
Build 09/20/2021from source, keybindings look great (there sure are a *lot* of them!)
OS: Elementary 6.0 

- menu/S-F10 doesn't seem to do anything?

**Comment by phase1geo** [comment]
Shift-F10 will produce a contextual menu for the currently selected annotation item (if one exists) or for the annotation item under the cursor (if one exists). Otherwise, it will not have an effect.

**Comment by QWxleA** [comment]
Thanks for the explanation, the fix, and the excellent app!
