### ISSUE TITLE
Missing arrows

### ISSUE THREAD

**Issue by QWxleA** [phase1geo/Annotator#16]
I tried drawing an arrow, but it looked horrible. Drawing a straight line is hard!

Pointing out things in images would be nice. Arrows would be needed for that. They might be hard to implement, in that case, an image of an arrow that can be rotated/pointed would be a good stop-gap.

**Comment by phase1geo** [comment]
Arrows are considered shapes and can be found under the shapes button in the toolbar. No need to draw them by hand…

**Comment by phase1geo** [comment]
FYI, straight lines are also considered to be a "shape" which is available in the shapes dropdown list.

**Comment by QWxleA** [comment]
And an excellent arrow it is! In my defence, arrows are so important they *deserve* their own space in the limelight / headerbar.

Once again want to point out I love this app.
