### ISSUE TITLE
annotated image not saving text box location

### ISSUE THREAD

**Issue by delta1071** [phase1geo/Annotator#29]
Hello and thank you for your efforts in creating this wonderful app! I'm running the latest Annotator Flatpak on my Ubuntu 20.4.3 machine. I opened an existing desktop background image file with Annotator, then added a new text box, added text and configured font, font size, color, etc. Then I moved the box to different location on the image. I then exported the modified image with a new name to a .png file in my user account Pictures folder. However, the image is exported with the text box in the location where it was originally created. I have tried this multiple times and the outcome is the same (also occurs when exporting to a different file type (e.g. jpeg).

**Comment by phase1geo** [comment]
I will take a look.

**Comment by phase1geo** [comment]
I wasn't able to reproduce this problem.

**Comment by delta1071** [comment]
And I am also not able to reproduce this behavior any more. Maybe just a temporary glitch that has worked itself out. Thanks for taking the time to investigate!
