### ISSUE TITLE
Add the ability to take a screenshot

### ISSUE THREAD

**Issue by oz123** [phase1geo/Annotator#3]
@phase1geo this is a really nice piece of software! Thank you for putting it out for the world!

I was wondering if it is going to be hard to add the ability to directly take a screenshot. It would be really nice to add
a button for it. Also, a command line flag for this, would allow using it as the default screenshot app instead of the default
GNOME\Mate screenshot app.

I am not fluent with vala, but with some guidance on where to start I could give it a try.

**Comment by phase1geo** [comment]
I'm wondering how feasible this is going to be.  I was looking at elementary's screenshot application, and it appears that it is using a Gnome screenshot API under the hood.  I don't see anything in the list of libraries available to Vala that provides direct screenshot functionality.  So if the capability is based on something lower-level then we will have the difficulty of supporting this feature for different variants of OS.

Your thoughts?

**Comment by hanaral** [comment]
Considering this *is* an AppCenter app, you could make the argument that elementary OS allows you to screenshot from the headerbar context menu now so it isn't necessary.

**Comment by phase1geo** [comment]
Holy cow! I didn't know that this feature exists in Odin. Super cool!

Most OSes have the ability to screenshot natively, so I'm not sure that the feature request is invalidated by this feature in elementary.

I understand the simplicity of opening up Annotator, creating a screenshot from within the application, and immediately start editing the file.  I'm just not sure how to implement this functionality at this point.  I don't know that Vala has any screenshotting APIs available to it.  If it doesn't, then it would need to ask something outside of the application to provide this information which may not be distribution independent.
