### ISSUE TITLE
Can not open image from Ubuntu (missing org.elementary.Contractor)

### ISSUE THREAD

**Issue by PandaJim** [phase1geo/Annotator#35]
It seems that the app depends on "org.elementary.Contractor" to import images, makes it impossible to use in Ubuntu without Flatpak

** (com.github.phase1geo.annotator:4336): CRITICAL **: 22:16:08.096: file ../../src/MainWindow.vala: line 299: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.elementary.Contractor was not provided by any .service files (g-dbus-error-quark, 2)

**Comment by phase1geo** [comment]
Which version of Annotator do you have installed? Are you using the Flatpak or a Debian package?

**Comment by PandaJim** [comment]
It's the initial 1.0.0 version built from source (debian package). Source file downloaded from the github releases page.

**Comment by PandaJim** [comment]
Oh, sorry it seems to be issue of my PNG file itself. The app works after using another image. And, thanks for the great app, especially for the magnifier!
