### ISSUE TITLE
Reduce minimum size for shapes

### ISSUE THREAD

**Issue by waldyrious** [phase1geo/Annotator#36]
I wanted to blur out a single line of text, but I can't seem to reduce the height (or width) of the blur box past a certain size. This seems to happen with other shapes too.

Say, for example that I wanted to circle the number 2 in this image:
![Screenshot from 2021-11-28 20-23-12](https://user-images.githubusercontent.com/478237/143784614-ba5e4cf4-6b3a-434f-becf-61fd99472b5e.png)

I can't because that's the smallest I can make the circle...

**Comment by phase1geo** [comment]
I'll see what I can do.  The selection rectangle needs to be large enough to allow the display of all of the drag handles such that they don't overlap with each other.  Perhaps what I could do is to remove the display of the some of the drag handles if the rectangle gets too small -- this should allow the rectangle to be smaller than the current minimum.

**Comment by phase1geo** [comment]
The master branch has been updated to provide support for resizing shapes and blur boxes smaller than the previous minimum requirements.
