### ISSUE TITLE
Jpeg quality

### ISSUE THREAD

**Issue by akovia** [phase1geo/Annotator#52]
Arch Linux Aur

Was trying this out and found a few things.

The default jpg quality is too low for publication. Really needs a setting somewhere to choose quality for the different formats.

The other thing is it appears you are outputting jpgs with the **jpeg** extension. This prevents from seeing existing jpg files in a folder to use a filename for saving among other issues. Would you consider changing it to jpg instead, or supporting both? (jpeg,jpg) 

Possibly allowing to save as "All Files" so you can see all the files in a folder you are saving in?

I can't wait to see this software mature. Linux is in such need of a good annotation tool, and this looks like it would fit the bill if not for a few minor issues.

Thanks for the hard work!

**Comment by phase1geo** [comment]
I have committed changes to the master branch that have revamped the UI for exporting that provides options for the supported export types.  This includes image quality for JPEG.  I have also changed the default save extension to .jpg, and have updated the JPEG supported extensions to include both.

I did not add support for an "All Files" view option, however.
