### ISSUE TITLE
Support custom border color

### ISSUE THREAD

**Issue by waldyrious** [phase1geo/Annotator#56]
Currently I can only customize the color of a shape's fill. I can also customize the border width and dash pattern, but not its color. I would like to have the option to pick a border color (including adding transparency).

**Comment by phase1geo** [comment]
Shapes are either border-only (outline) or a borderless (fill).  Though you can change the settings of the border when a filled shape is selected, you aren't affecting its border.

If you wanted a shape with a border and fill, you would essentially just create a fill object, move it to the needed position and then create a border version of that shape and position it over the filled shape.

**Comment by waldyrious** [comment]
> Shapes are either border-only (outline) or a borderless (fill).

That's weird... my original goal was actually to use a borderless filled shape, but it seemed to have a border nonetheless. For example, note the dark border around the yellow shape:

![image](https://user-images.githubusercontent.com/478237/162632607-be21c582-1810-4746-aa97-71d657821bde.png)

**Comment by phase1geo** [comment]
Fill shapes do have a one pixel border that is automatically colored to guarantee contrast with the image and/or other shapes and items. It also helps to identify individual shapes if they are similarly colored and overlapping each other.

**Comment by waldyrious** [comment]
Right, so what I would like is the ability to have filled shapes with no border. Even if the one-pixel border is made visible during editing, I would like the exported image to not have it. Is that something you'd consider?

**Comment by phase1geo** [comment]
Why do you want that feature?

**Comment by waldyrious** [comment]
That's the effect I wanted to add to an image: a colored shape without border. Yes, I could achieve a similar effect with the border, but it is a styling preference I wanted for that particular image, just like the color of the fill, the shape used, etc.

**Comment by phase1geo** [comment]
Makes sense. Thanks for the clarification!

**Comment by phase1geo** [comment]
I have added a feature to show/hide an items "outline" from this border menu.  Technically, the outline of an item is not the same as a border (because both solid and border shapes both have an outline).  Feel free to grab the master branch and give this feature a try.
