### ISSUE TITLE
Annotator won't open anymore after closing it once [ubuntu 22.04]

### ISSUE THREAD

**Issue by tpandresfernandez** [phase1geo/Annotator#58]
Hi, 

I just wanna thank you for such an amazing app, it's the perfect complement to the screenshot utility that comes from Gnome in Ubuntu 22.04.

Unfortunately, as mentioned in the title, the application won't open anymore after closing it once :(

Maybe it's a thing of the PPA, not sure.

Please let me know if you need anything on my side to debug/fix this

**Comment by phase1geo** [comment]
If you run the application from the terminal, do you see any error output?

**Comment by joshuarestivo** [comment]
I'm experiencing this same issue, too. If I reboot, it'll open again, but only once. In my case, it's been installed through elementaryOS app center. When I dig into the plank config file, I ultimately come to this command: usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.phase1geo.annotator --file-forwarding com.github.phase1geo.annotator @@ %f @@

If I run the above command as is, it complains about '%f' not being found. If I substitute a valid file name, the command just completes quietly. If I grab a shell through flatpak, I can manually run 'com.github.phase1geo.annotator' but, again, it just quietly exits. Adding --help does throw the Usage dialog.

Thoughts on where to go with this?

**Comment by phase1geo** [comment]
I'm not sure how to debug flatpaks at the moment.  I think there is supposed to be a way to to this, but the last time I tried it, I was not successful.  I'll see what I can do.  If there is any way that you can download and build Annotator from source (./app install & ./app debug in the top-most source directory), we might be able to get to the bottom of the issue.  Running ./app debug will put you into a gdb debugger, so you will need to enter 'c' at the prompt to get the application to start launching.  If there are any bad code issues, hopefully we will see them in the debugger output when the application dies.

**Comment by phase1geo** [comment]
Out of curiosity, does Annotator open after a reboot?

**Comment by joshuarestivo** [comment]
It would open once after a reboot but never again (until the next reboot). I've since moved away from elementary OS so I'm not facing this issue anymore nor can of be of much help in troubleshooting it further.

**Comment by phase1geo** [comment]
For @tpandresfernandez, I'm wondering if this is some sort of case where the first time that you launch the application, the minder executable remains running (for some reason).  If you attempt to run another invocation of Minder while a minder process is still running, nothing will happen -- the second invocation will simply return without doing much of anything.

**Comment by WGandy** [comment]
I'm having this problem on Linux Mint. In my case I think it had to do with the last file I had open. It was on a network drive that no longer exists. I've since uninstalled Annotator and reinstalled it (via apt from the added repository) but still cannot open the app through the gui.

**Comment by phase1geo** [comment]
@WGandy I'm guessing that if you looked at your running processes, you will see one or more Annotator processes running. You will need to kill those before relaunching Annotator.

**Comment by phase1geo** [comment]
The next stable version of Annotator will be based on Gtk4 which uses a different mechanism for handling application processes and should be avoiding this issue.  I'm going to add the WONT_FIX label before closing this issue out after the next stable version is released.
