### ISSUE TITLE
Arrow default size, ubuntu 22.04

### ISSUE THREAD

**Issue by ssyurr** [phase1geo/Annotator#59]
Great app, thank you very much!
Would be great to have a smaller arrow size since arrow that is default now is tooo thick
have to resize every arrow I add, other than that app is perfect, much appreciated

**Comment by phase1geo** [comment]
If you wish, you could try to build and run Annotator from source.  That code base contains a new feature which allows you to create custom shapes and arrows which can be used just like the built in shapes and arrows. It should meet your need.

**Comment by dreamcat4** [comment]
hello
... wanted to try this so installed from source today. However when trying to launch the program (locally compiled) it just exits immediately with code 0

although I can run `--version` and it says `1.2.0`
