### ISSUE TITLE
not exporting files

### ISSUE THREAD

**Issue by LeonardoAragaoCode** [phase1geo/Annotator#60]
Annotator is not exporting files to folders. I'm using Ubuntu 22.04 LTS

**Comment by phase1geo** [comment]
I'm not having any issues exporting files from Annotator.  If you are using a Flatpak version, make sure that your Flatpak permissions are enabled to access your home folder.

**Comment by blain1972** [comment]
> I'm not having any issues exporting files from Annotator. If you are using a Flatpak version, make sure that your Flatpak permissions are enabled to access your home folder.

this solved for me. Thanks.
