### ISSUE TITLE
Can't type accented characters

### ISSUE THREAD

**Issue by eliocamp** [phase1geo/Annotator#61]
It seems that writing accented characters is not supported. If I try to write "á", it shows as an unaccented character. However, if I copy the character and paste it, it works:

![image](https://user-images.githubusercontent.com/8617595/181051935-2ec32769-8719-4cf0-b915-95c7afd2084c.png)

**Comment by phase1geo** [comment]
What is the procedure for typing an accented character on a QWERTY keyboard?  I'd like to be able to replicate this issue for testing/debugging purposes.  Annotator is using an IMMulticontext input method, so I would assume that special characters should be properly supported.

**Comment by jtojnar** [comment]
I am unable to reproduce it on Czech layout in GNOME session. I press the <kbd>´</kbd> dead key and then <kbd>a</kbd> key and `á` is inserted.

**Comment by eliocamp** [comment]
I do the same. Press the `'` key and then the letter. I'm using the default Spanish keyboard layout, if it helps.

**Comment by phase1geo** [comment]
When I switch the to the Spanish keyboard layout using the lastest master branch version of Annotator and follow the above input steps, I see the accented 'a' character show up.  I'm running on Fedora 37 (though I don't think that the distribution should matter in this case).
