### ISSUE TITLE
Clipboard not fully working for Wayland

### ISSUE THREAD

**Issue by cmprmsd** [phase1geo/Annotator#62]
Hey, great tool!

There is `com.github.phase1geo.annotator --use-clipboard` in order to get an image from clipboard and edit it directly.
This method does not work on Wayland.
Also `wl-paste | com.github.phase1geo.annotator` won't work as there is no flag for stdin. 

When you open Annotator and paste an image it will be opened in the editor. However, this is one step that could be skipped.

Also the way how image pasting works, while working on an annotation is quite disturbing.
E.g. I annotate an image with 20+ elements and accidentally press `ctrl+v`. All work is gone, as the revert button does not revert `paste` but the changes within the editor. This might be worth another issue though.

Keep up the good work!

**Comment by phase1geo** [comment]
I don't have an immediate answers as to why clipboard pasting via CLI in Wayland does not work.  I'm not sure how to go about triaging that issue, but I'll try.

I have gone ahead and created a new issue for the undo pasting issue -- that would be a bug/oversight on my part. #66

**Comment by phase1geo** [comment]
I have committed a change to the master branch that adds support for reading an image to annotate from standard input.

**Comment by phase1geo** [comment]
As for the --use-clipboard issue, what is the image filetype that is being copied to the clipboard?  I think that on X systems, the default filetype for images is image/png.  I see that Annotator is specifically looking for image/png filetypes for images.  I'm wondering if that is not sufficient for Wayland.

**Comment by phase1geo** [comment]
I have come up with an implementation for the Control-V issue.  See #66 for details.

**Comment by cmprmsd** [comment]
Thanks I'll test it asap!

**Comment by phase1geo** [comment]
The --use-clipboard option should work if the image type copied to the clipboard is image/png (that is what the Annotator clipboard is looking for and that is what Control-V uses as well).  Not sure why that doesn't work.  On elementary (which still uses X), the --use-clipboard option works as expected.  I'll need to do some investigation in that regard.  I believe that Fedora uses Wayland these days, so I'll use that for a test environment.

**Comment by cmprmsd** [comment]
@phase1geo 
I just noticed, that the buttons to export the image are greyed out, when you pipe to annotator with -i. 

Workaround is currently to press ctrl+c and ctrl+v which seems to activate the buttons.

**Comment by phase1geo** [comment]
I will take a look at that and get it fixed.  Thanks!

**Comment by phase1geo** [comment]
The latest master branch has this UI issue fixed when loading from standard input.  Good catch!

**Comment by cmprmsd** [comment]
Nice! Thank you 👍👍👍
