### ISSUE TITLE
Pasting image is irreversible

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Annotator#66]
Annotating an image and then accidentally pressing Control+V to paste something from the clipboard cannot be undone, leading to a loss of work.

**Comment by phase1geo** [comment]
I have committed a change to the master branch which adds a confirmation dialog before pasting over an image that has been annotated.  If the user chooses to continue with the image paste, the undo buffer is cleared as this is a non-reversible operation (effectively we are starting a new annotation at this point).

**Comment by cmprmsd** [comment]
I tested your solution and the warning message is great, thanks!
One thing. The counter for the bullet icons should be reset when confirming the message with yes :)

**Comment by phase1geo** [comment]
Excellent point!  I will get that fixed.

**Comment by phase1geo** [comment]
The sequence number issue should be solved in the master branch now.
