### ISSUE TITLE
Open files by dropping on the window

### ISSUE THREAD

**Issue by jtojnar** [phase1geo/Annotator#68]
It would be nice if I could drag a file from a file manager to the window to have Annotator open it.

**Comment by phase1geo** [comment]
I believe that you should be able to drag and drop a file on the Minder icon in the dock to open it.

**Comment by jtojnar** [comment]
Unfortunately, that is currently [not supported](https://www.github.com/micheleg/dash-to-dock/issues/49) by the dock I use.

**Comment by phase1geo** [comment]
I have added the ability to drag and drop an image onto the welcome screen of Annotator to start annotating the dropped image.  This feature has been committed to the master branch and will be available in the 1.3.0 release.

**Comment by phase1geo** [comment]
Release 2.0.0 version contains the required changes.
