### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by rmeissn** [phase1geo/Annotator#73]
My flatpak system (on Fedora 37) complains about outdated dependencies of Annotator:

```
Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.phase1geo.annotator

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.phase1geo.annotator
```

Would it be possible to update these?

**Comment by phase1geo** [comment]
I don't maintain a flatpak for Annotator outside of the one for the elementary OS app store.  I don't know who created that.

**Comment by rmeissn** [comment]
It seems you pushed an update that fixed this issue. 
I've added the elementary flatpak ref to my fedora system and can thus install packages from the elementary app store.
