### ISSUE TITLE
duplicate icon folders/files installed

### ISSUE THREAD

**Issue by xiota** [phase1geo/Annotator#74]
When installing with `DESTDIR="${pkgdir}" ninja -C build install`, several duplicate files/folders are created:
````
${pkgdir}/usr/share/icons/hicolor/128x128/
${pkgdir}/usr/share/icons/hicolor/128x128@2/
${pkgdir}/usr/share/icons/hicolor/16x16/
${pkgdir}/usr/share/icons/hicolor/16x16@2/
${pkgdir}/usr/share/icons/hicolor/24x24/
${pkgdir}/usr/share/icons/hicolor/24x24@2/
${pkgdir}/usr/share/icons/hicolor/32x32/
${pkgdir}/usr/share/icons/hicolor/32x32@2/
${pkgdir}/usr/share/icons/hicolor/48x48/
${pkgdir}/usr/share/icons/hicolor/48x48@2/
${pkgdir}/usr/share/icons/hicolor/64x64/
${pkgdir}/usr/share/icons/hicolor/64x64@2/
````

Do they serve any purpose?  If not, would be nice to remove them.

**Comment by phase1geo** [comment]
That's a good question.  I was following a convention that was established by the elementary OS development team at the time.  I think that the @2 directories were meant to contain a version of the icon useful for HiDPI displays.  I don't know if these are meaningful for other systems or not.

**Comment by xiota** [comment]
I did some searching, and to me, it looks like the @2 folders are a hack to work around some GTK idiosyncrasies/bugs/something.  GTK has changed, so don't know if it's still needed.

Not all distros use the @2 folders.  Some pages discussing them even recommended creating them by symlinking the normal folders.

What about:  Make the installer check whether the system @2 folders exist and are real folders.  If so, symlink the SVGs from the normal folders.  Otherwise, don't use them.

**Comment by phase1geo** [comment]
I would be willing to accept a pull request to address this issue, but I don't think this is something that I'm going to worry about changing.
