### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by bhenstra** [phase1geo/Annotator#77]
I run Debian Sid. I did install the following packages: meson valac debhelper golang-gir-gobject-2.0-dev golang-gir-glib-2.0-dev libgee-0.8-dev libgranite-dev libxml2-dev libgtk-3-dev libhandy-1-dev

I did run sudo ./app install for a aystem wide install. 

I am missing the following icons:
Pencil Tool
Crop Image

Please see the screenshot:
[Missing-Icons.jpg](https://ict-diensten.com/pub/img/Missing-Icons.jpg)

$ uname -a
Linux sonic 6.1.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.11-1 (2023-02-09) x86_64 GNU/Linux

$ /usr/bin/com.github.phase1geo.annotator --version
1.2.0

![Missing-Icons](https://user-images.githubusercontent.com/25803325/220747927-e3ba9899-1fe8-4f2a-a527-a72ff2aaa2fc.jpg)

**Comment by phase1geo** [comment]
Is there a gnome icon package available for install? I believe those icons come standard in gnome environments.

**Comment by ernstki** [comment]
Since this issue happens to double as a handy guide to almost-building on Debian, I'll add these two requirements to the list above: libportal-gtk4 and libportal-gtk4.

So:

```bash
sudo apt install meson valac debhelper golang-gir-gobject-2.0-dev \
         golang-gir-glib-2.0-dev libgee-0.8-dev libgranite-dev libxml2-dev \
         libgtk-3-dev libhandy-1-dev libportal-gtk4 and libportal-gtk4
```

**Comment by ernstki** [comment]
> Is there a gnome icon package available for install? I believe those icons come standard in gnome environments.

They are standard, and installed, but still.

Here are the list of packages you get with a mostly-out-of-the-box Debian Unstable system, as of this writing:

```console
$ apt search --names-only 'gnome.*icon.*' 2>/dev/null | grep '\[installed'
gnome-brave-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-dust-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-human-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-icon-theme/unstable,testing,stable,now 3.12.0-5 all [installed,automatic]
gnome-illustrious-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-noble-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-wine-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
gnome-wise-icon-theme/unstable,testing,stable,now 5.5.1-2.1 all [installed,automatic]
```

**Comment by phase1geo** [comment]
I've been working on a GTK4 port of Annotator which should have all of these UI issues fixed (minus your icon fixes).

**Comment by ernstki** [comment]
@phase1geo Thanks for your efforts!
