### ISSUE TITLE
How to reset sequential number to start over from 1 again?

### ISSUE THREAD

**Issue by complyue** [phase1geo/Annotator#79]
I need multiple sets of sequences to be marked on a screenshot, like 1,2,3, then 1,2,3, how can I do that?

Thanks for the nice app!

**Comment by phase1geo** [comment]
There currently does not exist a way to reset the sequence numbers back to one. I can add that as a feature.

To work around the problem in the meantime, you can right click on a sequence number and change the displayed number from the contextual menu. You would have to do that for each sequence number though.

**Comment by phase1geo** [comment]
I have changed the sequence number behavior to increment from the last set sequence number.  This change has been committed to the master branch.
