### ISSUE TITLE
Can't take screenshots in Ubuntu 23.04

### ISSUE THREAD

**Issue by pablorq** [phase1geo/Annotator#86]
I can't take any screenshot (screen, window, area) in Ubuntu 23.04.

Tried with mouse clics and keyboard shortcuts with the same result: annotator window disappear for some seconds (the 3s delay) and then reappear in the same welcome page.

No --debug option on the CLI.

Any logs are generated? (Nothing in ~/.local/share/annotator)

Any idea of what can be happen?

**Comment by phase1geo** [comment]
Screenshots are not available on all systems at the current time.  I believe it is only supported for X11 systems and not for Flatpaks, I believe.  It's possible that the UI is still showing that this feature is available for your system (which I would consider to be a bug).

**Comment by celevra** [comment]
i'm on ubuntu 24.04 with X11 and using the .deb version
but can't use the screenshot feature

**Comment by phase1geo** [comment]
I'm able to run on Ubuntu 23.10 if I set "export GDK_BACKEND=x11" prior to running Annotator (Wayland is the default).

**Comment by phase1geo** [comment]
I think that I have implemented an improved solution which should fix this issue on Wayland systems.  Fix has been committed to the master branch and should be available in the 1.3.0 release.

**Comment by phase1geo** [comment]
Release 2.0.0 version contains the required changes.
