### ISSUE TITLE
Running native app results in core dump because Settings schema isn't installed

### ISSUE THREAD

**Issue by gtjoseph** [phase1geo/Annotator#91]
On Fedora 39...

Ran `./app run`.
Build was successful but on start got...
```
(com.github.phase1geo.annotator:2572520): GLib-GIO-ERROR **: 08:49:55.217: Settings schema 'com.github.phase1geo.annotator' is not installed
./app: line 44: 2572520 Trace/breakpoint trap   (core dumped) ./com.github.phase1geo.annotator "${@:2}"
```
Am I missing a step somewhere?

**Comment by phase1geo** [comment]
Yes, you will need to run './app install' prior to running with './app run'.

**Comment by gtjoseph** [comment]
Ah, OK.  That works.
I had wanted to test the app before installing and saw the following in ./app.
```
run               Builds and runs the application
```
You might want to update that to indicate that you have to have run `./app install` at least once to install all of the messages, icons and settings schema.

Thanks!

**Comment by phase1geo** [comment]
I have made an update to the app script to add extra documentation to the run command to include running the install command once before successive calls to run.  The changes are in the main branch.
