### ISSUE TITLE
Request: paste multiple images from clipboard

### ISSUE THREAD

**Issue by j-silv** [phase1geo/Annotator#92]
Hi there,

I have been trying to find a Linux equivalent to Microsoft Paint for a while. My previous attempts often failed because no software seemed as simple, intuitive, and lightweight as MS Paint. I stumbled upon this [article](https://www.omgubuntu.co.uk/2021/10/best-annotation-tool-for-linux-desktop) and thus decided to give the Annotator project a try. Image clipboard pasting seemed promising, and the toolbar seemed simple but with enough functionality to support my use cases.

However, after using Annotator I was disappointed to find no "multiple" image copying from clipboard functionality like Paint has. In other words, when we paste an image into the main Annotator window, it automatically resizes to the new image and erases that was previously there. Thus, we are unable to create an image with multiple source images.

What do you all think about this feature?

**Comment by phase1geo** [comment]
That's been a feature on my radar.  Currently, Annotator has support for inserting stickers (which are just images that are defined by the application), so there's not much required code-wise to implement this feature.

Once implemented, the feature will probably work just a bit differently than your proposal.  The behavior of pasting an image which replaces the image being annotated is the desired behavior.  What will probably happen is that you will be able to insert a shape and, when it is selected, pasting an image in the clipboard will have the effect of inserting the image into the shape.  The shape controls will then be used for scaling/stretching the image as desired.

**Comment by phase1geo** [comment]
FYI, I'm currently working on upgrading Annotator from GTK3 to GTK4 which turn into a 2.0 version of Annotator.  The embedded image support as described above would probably be added in a subsequent release after that.

**Comment by phase1geo** [comment]
FYI, Annotator is designed to be a replacement for an application like MS Paint.  It's features are designed around the concept of adding information to an existing image and outputting a new image that can be used elsewhere.  It doesn't have support for saving an annotated version of the image and it doesn't support creating images from scratch.  It also doesn't support manipulating individual pixels or performing destructive operations on the original image (such as erasing portions of the image).  I believe there are better equivalents to MS Paint in the world of open source tools if that is truly what you are looking for.

**Comment by phase1geo** [comment]
In the main branch, I have added support for embedding images within the main image.  This does not include support for clipping an image to a given shape at this point.  That functionality will be added in a later release.

**Comment by phase1geo** [comment]
Release 2.0.0 version contains the required changes for embedding images.
