### ISSUE TITLE
Segmentation fault when using delete key

### ISSUE THREAD

**Issue by caribo** [phase1geo/Annotator#95]
Annotator crashes when using delete key.

1) Open file
2) Draw line using Pen
3) Press Delete

> zsh: segmentation fault (core dumped)  com.github.phase1geo.annotator 

Delete using the right click context menu seems to work okay, but when using delete key it crashes.

Running on Manjaro - source compiled from AUR - http://aur.archlinux.org/packages/annotator

gdb shows:-

Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
0x0000555555572f7c in ?? ()

**Comment by heroin-moose** [comment]
Yeah, same, still an issue.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.
