### ISSUE TITLE
CLI option --use-clipboard doesn't work

### ISSUE THREAD

**Issue by ArkadyBuryakov** [phase1geo/Annotator#99]
## Description

Running `annotator --use-clipboard` acts the same as running just `annotator`.

### Steps

1. Copy image to clipboard
2. Run `annotator --use-clipboard`

### Result

Annotator started with empty workspace

### Expected result

Annotator started with opened image from clipboard

## Comments

Pasting image from clipboard to a running Annotator works fine.

I am running annotator on Arch with Hyprland.
version 1.2.1-1 from AUR

**Comment by phase1geo** [comment]
FYI, I have just pushed the fix for the --standard-input (or -i) option to the master branch.  If you are interested in compiling from source and trying it out, it is available from GitHub.

**Comment by ArkadyBuryakov** [comment]
I can confirm that --standard-input workaround works fine with commit `a9ec965` version
